{
    "name": "tesa",
    "version": "0.0.20dev",
    "author": "Telosoft",
    "category": "Tools",
    "website": "http://www.telosoft.com",
    "description": """Provides an ERP Implementation and Customization Addon (Version 0.0.20dev)""",
    "depends": [
        "base",
        "account_accountant",
        "sale",
        "stock",
        "purchase",
        "hr",
        "contacts",
        "account_asset",
        "account_cancel",
        "stock_reserve_sale",
        "partner_credit_limit",
        "purchase_discount",
        "web_export_view",
        "disable_openerp_online",
        "stock_picking_locations",
        "sale_add_products_wizard",
        "sale_order_line_view",
    ],
    "init_xml": [
    ],
    "update_xml": [
    ],
    "data": [
        "views/base.xml",
        "views/product.xml",
        "views/brand.xml",
        "views/partner.xml",
        "views/stock.xml",
        "views/sale.xml",
        "views/purchase.xml",
        "views/flowchart.xml",
        "views/search.xml",
        "views/_menu.xml",
        "security/ir.model.access.csv",
    ],
    "qweb" : [
        "static/src/xml/base.xml",
        "static/src/xml/flowchart.xml",
        "static/src/xml/search.xml",
    ],
    "installable": True,
    "auto_install": False,
}
